# Quando parte
trigger:
  branches:
      include:
        - DEV
        - UAT
        - main

# Crea una macchina virtuale con l'ultima versione di ubuntu
pool:
  vmImage: ubuntu-latest

# Cose che deve fare
steps:

# Primo step
- script: |

    # Stampa che inizia la build
    echo "Inizio build"

    # Controlla che esista un file chiamato index.html
    test -f index.html

    # Crea una cartella chiamata build dove andrà il file buildato (solo copiato in questo caso)
    mkdir build

    # Copia il file nella cartella build per simulare
    cp index.html build/

    # Stampa che ha finito
    echo "Build terminata"

  # Assegna un nome allo step
  displayName: Build


# Salva i risultati della build
- task: PublishBuildArtifacts@1

  # Parametri della funzione
  inputs:

    # Dice quale cartella deve pubblicare
    PathtoPublish: 'build'

    # Da un nome all'artifact
    ArtifactName: 'website'

  # Nome dello step
  displayName: 'Pubblica Artifact'

# Esplicita chi ha chiamato l'artifatto
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build'
    ArtifactName: '$(Build.SourceBranchName)'
  displayName: 'Pubblica Artifact'
