jobs:

  deploy-dev:
    if: github.event.workflow_run.head_branch == 'DEV'
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - run: echo "Deploy DEV"

  deploy-uat:
    if: github.event.workflow_run.head_branch == 'UAT'
    runs-on: ubuntu-latest
    environment: UAT

    steps:
      - run: echo "Deploy UAT"

  deploy-prod:
    if: github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - run: echo "Deploy PROD"
